export const info1 = {
    id: 'info1',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Topline',
    headline: 'This is headline',
    description: 'This is description',
    buttonLabel: 'Details',
    imgStart: false,
    img: require('../images/i1.jpg'),
    alt: 'Something',
    dark: true,
    primary: true,
    darkText: false,
}

export const info2 = {
    id: 'info2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Topline',
    headline: 'This is headline',
    description: 'This is description',
    buttonLabel: 'Details',
    imgStart: false,
    img: require('../images/i2.jpeg'),
    alt: 'Something',
    dark: false,
    primary: false,
    darkText: true,
}

export const info3 = {
    id: 'info3',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Topline',
    headline: 'This is headline',
    description: 'This is description',
    buttonLabel: 'Details',
    imgStart: false,
    img: require('../images/i3.jpg'),
    alt: 'Something',
    dark: true,
    primary: true,
    darkText: false,
}