export const eventcategory1 = {
    id: 'ec1',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Cultural',
    headline: 'This is headline',
    description: 'This is description',
    buttonLabel: 'Details',
    imgStart: false,
    img: require('../images/i1.jpg'),
    alt: 'Something',
    dark: true,
    primary: true,
    darkText: false,
}

export const eventcategory2 = {
    id: 'ec2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Technical',
    headline: 'This is headline',
    description: 'This is description',
    buttonLabel: 'Details',
    imgStart: false,
    img: require('../images/i2.jpeg'),
    alt: 'Something',
    dark: false,
    primary: false,
    darkText: true,
}

export const eventcategory3 = {
    id: 'ec3',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Sports',
    headline: 'This is headline',
    description: 'This is description',
    buttonLabel: 'Details',
    imgStart: false,
    img: require('../images/i3.jpg'),
    alt: 'Something',
    dark: true,
    primary: true,
    darkText: false,
}